version: 2.1

executors:
  main-executor:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo

jobs:
  build:
    executor: main-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

            - v1-server-dependencies-{{ checksum "cypress/server/package.json" }}
            - v1-server-dependencies-

            - v1-example-dependencies-{{ checksum "example/package.json" }}
            - v1-example-dependencies-

      - run: yarn install
      - run: $(npm bin)/cypress install

      - save_cache:
          paths:
            - node_modules
            - /home/circleci/.cache/Cypress
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd cypress/server && yarn install

      - save_cache:
          paths:
            - cypress/server/node_modules
          key: |
            v1-server-dependencies-{{ checksum "cypress/server/package.json" }}

      - run: cd example && yarn install

      - save_cache:
          paths:
            - example
          key: v1-example-dependencies-{{ checksum "example/package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - dist/
            - node_modules/
            - example/node_modules/
            - cypress/server/node_modules/

  run-cypress:
    executor: main-executor
    steps:
      - attach_workspace:
          at: .

      - run: mkdir cypress-test-results
      - run: yarn cypress:ci
      - store_test_results:
          path: cypress-test-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  run-linters:
    executor: main-executor
    steps:
      - attach_workspace:
          at: .

      - checkout

      - run: yarn lint:js
      - run: yarn lint:css
workflows:
  version: 2
  main:
    jobs:
      - build
      - run-cypress:
          requires:
            - build
      - run-linters:
          requires:
            - build
