# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

            - v1-server-dependencies-{{ checksum "cypress/server/package.json" }}
            - v1-server-dependencies-

      - run: yarn install
      - run: $(npm bin)/cypress install

      - save_cache:
          paths:
            - node_modules
            - /home/circleci/.cache/Cypress
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd cypress/server && yarn install

      - save_cache:
          paths:
            - cypress/server/node_modules
          key: |
            v1-server-dependencies-{{ checksum "cypress/server/package.json" }}

      # Run Cypress tests
      - run: mkdir cypress-test-results
      - run: yarn cypress:ci
      - store_test_results:
          path: cypress-test-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

      # Run linters
      - run: yarn lint:js
      - run: yarn lint:css
