version: 2.1

executors:
  main-executor:
    docker:
      - image: cypress/base:10
    working_directory: ~/react-modern-sticky

jobs:
  build:
    executor: main-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          keys:
            - v1-server-dependencies-{{ checksum "cypress/server/package.json" }}
            - v1-server-dependencies-
      - restore_cache:
          keys:
            - v1-example-dependencies-{{ checksum "example/package.json" }}
            - v1-example-dependencies-
      - restore_cache:
          keys:
            - v1-cypress-{{ checksum "package.json" }}
            - v1-cypress-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd cypress/server && yarn install
      - save_cache:
          paths:
            - cypress/server/node_modules
          key: |
            v1-server-dependencies-{{ checksum "cypress/server/package.json" }}

      - run: cd example && yarn install
      - save_cache:
          paths:
            - example/node_modules
          key: v1-example-dependencies-{{ checksum "example/package.json" }}

      - save_cache:
          paths:
            - ~/react-modern-sticky
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  run-cypress:
    executor: main-executor
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run: $(npm bin)/cypress install

      - run: mkdir -p test-results/cypress
      - run: |
          yarn cypress:ci --reporter junit \
          --reporter-options "mochaFile=test-results/cypress/results.xml,toConsole=true"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  run-linters:
    executor: main-executor
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run: yarn lint:js
      - run: yarn lint:css
workflows:
  version: 2
  main:
    jobs:
      - build
      - run-cypress:
          requires:
            - build
      - run-linters:
          requires:
            - build
